CRUD/Models/ViewModels/ClienteViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CRUD.Models.ViewModels
{
    public class ClienteViewModel
    {

        public int id_cli { get; set; }
        [Required]
        [Display(Name = "Nombre")]
        [StringLength(50)]
        public string nombre_cli { get; set; }
        [Required]
        [Display(Name = "Cedula")]
        [StringLength(10)]
        public string cedula_cli { get; set; }
        [Required]
        [Display(Name = "Correo")]
        [StringLength(80)]
        [EmailAddress]
        public string correo_cli { get; set; }
        [Required]
        [Display(Name = "Fecha de Nacimiento")]
       // [DataType(DataType.Date)]
       // [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode =true)]
        public DateTime fechaNacimiento_cli { get; set; }

        [Required]
        [Display(Name = "Imagen")]
        public String imagen { get; set; }

    }
}

CRUD/Models/cliente.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public int id_cli { get; set; }
        public string nombre_cli { get; set; }
        public string cedula_cli { get; set; }
        public string correo_cli { get; set; }
        public Nullable<System.DateTime> fechaNacimiento_cli { get; set; }
        public string imagen { get; set; }
    }
}

CRUD/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CRUD.Models;
using CRUD.Models.ViewModels;

namespace CRUD.Controllers
{
    public class ClienteController : Controller
    {
        // GET: Cliente
        public ActionResult Index()
        {
            List<ListClienteViewModel> lst;
            using (facturaEntities db = new facturaEntities())
            {
                lst = (from d in db.cliente
                        select new ListClienteViewModel
                        {
                            id_cli = d.id_cli,
                            nombre_cli = d.nombre_cli,
                            correo_cli = d.correo_cli,
                            imagen = d.imagen
                        }).ToList();
            }
                return View(lst);
        }

        public ActionResult Nuevo()
        {
            return View();
        }
        [HttpPost]

        public ActionResult Nuevo(ClienteViewModel clientemodel)
        {
            try
            {
                //Validar los data Annotations
                if(ModelState.IsValid)
                {
                    //Si todo es valido vamos a guardar los datos en la base de datos 
                    using(facturaEntities db = new facturaEntities())
                    {
                        var oCliente = new cliente();
                        oCliente.id_cli = clientemodel.id_cli;
                        oCliente.nombre_cli = clientemodel.nombre_cli;
                        oCliente.cedula_cli = clientemodel.cedula_cli;
                        oCliente.correo_cli = clientemodel.correo_cli;
                        oCliente.fechaNacimiento_cli = clientemodel.fechaNacimiento_cli;
                        oCliente.imagen = clientemodel.imagen;

                        db.cliente.Add(oCliente);
                        db.SaveChanges();
                    }
                    return Redirect("~/Cliente/Index");
                }
                return View(clientemodel);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
           
        }

        public ActionResult Editar(int id)
        {
            ClienteViewModel model = new ClienteViewModel();
            using(facturaEntities db = new facturaEntities())
            {
                var oCliente = db.cliente.Find(id);
                model.nombre_cli = oCliente.nombre_cli;
                model.cedula_cli = oCliente.cedula_cli;
                model.correo_cli = oCliente.correo_cli;
                model.fechaNacimiento_cli = (DateTime)oCliente.fechaNacimiento_cli;
                model.imagen = oCliente.imagen;
                model.id_cli = oCliente.id_cli;
            }
            return View(model);
        }
        [HttpPost]

        public ActionResult Editar(ClienteViewModel clientemodel)
        {
            try
            { 
                //Validar los data Annotations
                if (ModelState.IsValid)
                {
                    //Si todo es valido vamos a guardar los datos en la base de datos 
                    using (facturaEntities db = new facturaEntities())
                    {
                        var oCliente = new cliente();
                        oCliente.id_cli = clientemodel.id_cli;
                        oCliente.nombre_cli = clientemodel.nombre_cli;
                        oCliente.cedula_cli = clientemodel.cedula_cli;
                        oCliente.correo_cli = clientemodel.correo_cli;
                        oCliente.fechaNacimiento_cli = clientemodel.fechaNacimiento_cli;
                        oCliente.imagen = clientemodel.imagen;

                        db.Entry(oCliente).State= System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                    return Redirect("~/Cliente/Index");
                }
                return View(clientemodel);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }

        }

        
        public ActionResult Eliminar(int id_cli)
        {
            using(facturaEntities db = new facturaEntities())
            {
                var oCliente = db.cliente.Find(id_cli);
                db.cliente.Remove(oCliente);
                db.SaveChanges();

            }
            return Redirect("~/Cliente/Index");
        }

    }


}

CRUD/Views/Cliente/Editar.cshtml
@model CRUD.Models.ViewModels.ClienteViewModel
@{
    ViewBag.Title = "Editar Cliente";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Editar", "cliente", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12 ">

            @Html.HiddenFor(d => d.id_cli)
            <div>
                @Html.LabelFor(d => d.nombre_cli)
                @Html.TextBoxFor(d => d.nombre_cli, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.nombre_cli, null, new { @class = "red" })
            </div>

            <div>
                @Html.LabelFor(d => d.cedula_cli)
                @Html.TextBoxFor(d => d.cedula_cli, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.cedula_cli, null, new { @class = "red" })
            </div>

            <div>
                @Html.LabelFor(d => d.correo_cli)
                @Html.TextBoxFor(d => d.correo_cli, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.correo_cli, null, new { @class = "red" })
            </div>


            <div>
                @Html.LabelFor(d => d.fechaNacimiento_cli) <br />
                @Html.EditorFor(d => d.fechaNacimiento_cli, new { htmlAttributes = new { @class = "datepicker" } })
                @Html.ValidationMessageFor(d => d.fechaNacimiento_cli, null, new { @class = "red" })
            </div>

            <div>
                @Html.LabelFor(d => d.imagen)
                @Html.TextBoxFor(d => d.imagen, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.imagen, null, new { @class = "red" })
            </div>

            <br />
            <div>
                <input value="Actualizar" class="btn btn-primary" type="submit" />
            </div>


        </div>

    </div>
}

<link href="~/Scripts/jquery-ui.min.css" rel="stylesheet" />
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

@section scripts{
    <script src="~/Scripts/jquery-ui.min.js"></script>
    <script>
        $(function () {
            $(".datepicker").datepicker({
                dateFormat: "yy/mm/dd",
                changeMonth: true,
                changeYear: true,
                //yearRange:"-10:+10"
                minDate: new Date(1992, 0, 1),
                maxDate: new Date(2008, 0, 1),
                showOn: "both",

            });
        });
    </script>
}

CRUD/Views/Cliente/Index.cshtml
@model List<CRUD.Models.ViewModels.ListClienteViewModel>
@{
    ViewBag.Title = "Usuarios";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-md-12">
        <div class="row col-1" style="text-align:left; padding:10px;">
            <a href="~/Cliente/Nuevo" class="btn btn-primary">Nuevo</a>
        </div>
        <table class="table table-bordered">
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Correo</th>
                <th>Imagen</th>
            </tr>
            @foreach (var oElemento in Model)
            {
                <tr>
                    <td>@oElemento.id_cli</td>
                    <td>@oElemento.nombre_cli</td>
                    <td>@oElemento.correo_cli</td>
                    <td><img width="150" height="150" src="@oElemento.imagen" /></td>
                    <td>
                        <a class="btn btn-success" href="@Url.Action("Editar", "Cliente", new {id = oElemento.id_cli})">Editar</a>
                        <a class="btn btn-danger" onclick="return confirm('¿Esta seguro que quiere eliminar el usuario?');" href="@Url.Action("Eliminar", "Cliente", new { id_cli =oElemento.id_cli})">Eliminar</a>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

CRUD/Views/Cliente/Nuevo.cshtml
@model CRUD.Models.ViewModels.ClienteViewModel
@{
    ViewBag.Title = "Agregar un Cliente";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Nuevo", "cliente", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12 ">


            <div>
                @Html.LabelFor(d => d.nombre_cli)
                @Html.TextBoxFor(d => d.nombre_cli, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.nombre_cli, null, new { @class = "red" })
            </div>

            <div>
                @Html.LabelFor(d => d.cedula_cli)
                @Html.TextBoxFor(d => d.cedula_cli, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.cedula_cli, null, new { @class = "red" })
            </div>

            <div>
                @Html.LabelFor(d => d.correo_cli)
                @Html.TextBoxFor(d => d.correo_cli, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.correo_cli, null, new { @class = "red" })
            </div>


            <div>
                @Html.LabelFor(d => d.fechaNacimiento_cli) <br />
                @Html.EditorFor(d => d.fechaNacimiento_cli, new { htmlAttributes = new { @class = "datepicker" } })
                @Html.ValidationMessageFor(d => d.fechaNacimiento_cli, null, new { @class = "red" })
            </div>

            <div>
                @Html.LabelFor(d => d.imagen)
                @Html.TextBoxFor(d => d.imagen, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.imagen, null, new { @class = "red" })
            </div>

            <br />
            <div>
                <input value="Guardar" class="btn btn-primary" type="submit" />
            </div>


        </div>

    </div>

    <link href="~/Scripts/jquery-ui.min.css" rel="stylesheet" />
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

    @section scripts{
        <script src="~/Scripts/jquery-ui.min.js"></script>
        <script>
            $(function () {
                $(".datepicker").datepicker({
                    dateFormat: "yy/mm/dd",
                    changeMonth: true,
                    changeYear: true,
                    //yearRange:"-10:+10"
                    minDate: new Date(1992, 0, 1),
                    maxDate: new Date(2008, 0, 1),
                    showOn: "both",

                });
            });
        </script>
    }
}